const items = [
  { name: 'Футболка', category: 'Одяг', price: 25.99 },
  { name: 'Джинси', category: 'Одяг', price: 49.99 },
  { name: 'Кросівки', category: 'Взуття', price: 79.99 },
  { name: 'Ноутбук', category: 'Електроніка', price: 899.99 },
  { name: 'Смартфон', category: 'Електроніка', price: 599.99 },
  { name: 'Чайник', category: 'Побутова техніка', price: 29.99 },
  { name: 'Тостер', category: 'Побутова техніка', price: 39.99 },
  { name: 'Шампунь', category: 'Краса та догляд', price: 9.99 },
  { name: 'Крем для обличчя', category: 'Краса та догляд', price: 14.99 },
  { name: 'Шкарпетки', category: 'Одяг', price: 9.99 },
  { name: 'Пенал', category: 'Приладдя', price: 19.99 },
  { name: 'Ручка', category: 'Приладдя', price: 2.99 },
  { name: 'Мило', category: 'Краса та догляд', price: 4.99 },
  { name: 'Парасолька', category: 'Аксесуари', price: 17.99 },
  { name: 'Флешка', category: 'Електроніка', price: 12.99 },
  { name: 'Книга', category: 'Книги', price: 15.99 },
  { name: 'Мяч', category: 'Спортивні товари', price: 7.99 },
  { name: 'Пляшка для води', category: 'Спортивні товари', price: 4.99 },
  { name: 'Чохол для телефону', category: 'Аксесуари', price: 8.99 },
  { name: 'Клавіатура', category: 'Електроніка', price: 49.99 },
];
